
#include "SetStyle.C"

void plotS3B6D0( string VarName,TPaveText *txtGen , TH1F *hs1 , string sig_proc1, TH1F *hs2 , string sig_proc2, TH1F *hs3 , string sig_proc3
,  TH1F *hb1  , string bkg_proc1 ,  TH1F *hb2  , string bkg_proc2 ,  TH1F *hb3  , string bkg_proc3 ,  TH1F *hb4  , string bkg_proc4 ,  TH1F *hb5  , string bkg_proc5 ,  TH1F *hb6  , string bkg_proc6 ){
using namespace std;
TStyle *gStyle = new TStyle("gStyle","Style for P-TDR");
SetStyle st;
st.SetPars(gStyle);
char Variable[100];
char Cname[100];
const char *Var_Name;
Var_Name=VarName.c_str();
sprintf(Variable," ;%s; Events",Var_Name);
sprintf(Cname,"%s",Var_Name);
TPaveText *pCMS = new TPaveText(0.132107,0.9308003,0.8327759,0.9923583,"brNDC");
pCMS->SetBorderSize(0);
pCMS->SetFillStyle(0);
pCMS->SetTextAlign(11);
pCMS->SetTextFont(42);
pCMS->SetTextSize(0.04);
pCMS->AddText("CMS #it{Preliminary}                   35.9 fb^{-1}, #sqrt{s}= 13 TeV");
TLegend *leg=new TLegend(0.3582943,0.7051483,0.55025753,0.9049564,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(1);
leg->SetLineStyle(1);
leg->SetLineWidth(3);
leg->SetFillColor(0);
leg->SetFillStyle(1001);
leg->SetShadowColor(0);
leg->SetDrawOption(0);
leg->SetBorderSize(0);
leg->SetTextSize(0.03);
THStack *hallbkg=new THStack("hallbkg",Variable);
hb1->SetFillColor(2);
hb1->SetLineColor(1);
hallbkg->Add(hb1);
char h1L_bkg[100];
const char *h1_L_bkg;
h1_L_bkg=bkg_proc1.c_str();
sprintf(h1L_bkg,"%s",h1_L_bkg);
leg->AddEntry(hb1,h1L_bkg,"f");
hb2->SetFillColor(3);
hb2->SetLineColor(1);
hallbkg->Add(hb2);
char h2L_bkg[100];
const char *h2_L_bkg;
h2_L_bkg=bkg_proc2.c_str();
sprintf(h2L_bkg,"%s",h2_L_bkg);
leg->AddEntry(hb2,h2L_bkg,"f");
hb3->SetFillColor(4);
hb3->SetLineColor(1);
hallbkg->Add(hb3);
char h3L_bkg[100];
const char *h3_L_bkg;
h3_L_bkg=bkg_proc3.c_str();
sprintf(h3L_bkg,"%s",h3_L_bkg);
leg->AddEntry(hb3,h3L_bkg,"f");
hb4->SetFillColor(5);
hb4->SetLineColor(1);
hallbkg->Add(hb4);
char h4L_bkg[100];
const char *h4_L_bkg;
h4_L_bkg=bkg_proc4.c_str();
sprintf(h4L_bkg,"%s",h4_L_bkg);
leg->AddEntry(hb4,h4L_bkg,"f");
hb5->SetFillColor(6);
hb5->SetLineColor(1);
hallbkg->Add(hb5);
char h5L_bkg[100];
const char *h5_L_bkg;
h5_L_bkg=bkg_proc5.c_str();
sprintf(h5L_bkg,"%s",h5_L_bkg);
leg->AddEntry(hb5,h5L_bkg,"f");
hb6->SetFillColor(7);
hb6->SetLineColor(1);
hallbkg->Add(hb6);
char h6L_bkg[100];
const char *h6_L_bkg;
h6_L_bkg=bkg_proc6.c_str();
sprintf(h6L_bkg,"%s",h6_L_bkg);
leg->AddEntry(hb6,h6L_bkg,"f");
hs1->SetFillStyle(1);
hs1->SetLineColor(1);
char h1L_sig[100];
const char *h1_L_sig;
h1_L_sig=sig_proc1.c_str();
sprintf(h1L_sig,"%s",h1_L_sig);
leg->AddEntry(hs1,h1L_sig,"l");
hs2->SetFillStyle(1);
hs2->SetLineColor(1);
char h2L_sig[100];
const char *h2_L_sig;
h2_L_sig=sig_proc2.c_str();
sprintf(h2L_sig,"%s",h2_L_sig);
leg->AddEntry(hs2,h2L_sig,"l");
hs3->SetFillStyle(1);
hs3->SetLineColor(1);
char h3L_sig[100];
const char *h3_L_sig;
h3_L_sig=sig_proc3.c_str();
sprintf(h3L_sig,"%s",h3_L_sig);
leg->AddEntry(hs3,h3L_sig,"l");
TCanvas *c=new TCanvas(Cname,Cname);
c->cd();
hallbkg->Draw("hist");
hallbkg->GetYaxis()->SetTitle("Events");
hallbkg->Draw("hist");
hs1->Draw("same");
hs2->Draw("same");
hs3->Draw("same");
txtGen->Draw();
pCMS->Draw();
leg->Draw();
c->Write();
}


